name: anydesk_resetter
description: "Resets AnyDesk ID/Ads."
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  very_good_analysis: ^7.0.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/anydesk_logo_1.png

build_options:
  aot:
    obfuscate: true
    split-debug-info: build/app/outputs/symbols